//Empresa
export const MOSTRAR_EMPRESAS = 'MOSTRAR_EMPRESAS';
export const CREANDO_EMPRESA = 'CREANDO_EMPRESA';
export const CREAR_EMPRESA_EXITO = 'CREAR_EMPRESA_EXITO';
export const CREAR_EMPRESA_ERROR = 'CREAR_EMPRESA_ERROR';
export const ACTUALIZANDO_EMPRESA = 'ACTUALIZANDO_EMPRESA';
export const ACTUALIZAR_EMPRESA_EXITO = 'ACTUALIZAR_EMPRESA_EXITO';
export const ACTUALIZAR_EMPRESA_ERROR = 'ACTUALIZAR_EMPRESA_ERROR';
export const ELIMINANDO_EMPRESA = 'ELIMINANDO_EMPRESA';
export const ELIMINAR_EMPRESA_EXITO = 'ELIMINAR_EMPRESA_EXITO';
export const ELIMINAR_EMPRESA_ERROR = 'ELIMINAR_EMPRESA_ERROR';

//Generales
export const SUBIR_ARCHIVO = 'SUBIR_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';